### ISSUE TITLE
App crashes on Samsung S6 with Android 5.1.1 on startup because it cannot initialize renderscript

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessAndroid#73]
This thread seems to explain what is going on:
https://code.google.com/p/android/issues/detail?id=182356

This is a link to the issue in crashalytics:
https://fabric.io/theotech/android/apps/org.theotech.ceaselessandroid/issues/56a14128f5d3a7f76b3eb063/sessions/56a1aba300240001617b51a7ac589f0b

**Comment by chrislim** [comment]
An Android 6.0 Nexus 5X device encountered a similar issue:

java.lang.RuntimeException: Transformation BlurTransformation(radius=25, sampling=2) crashed with exception.
	at com.squareup.picasso.BitmapHunter$3.run(BitmapHunter.java:434)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.support.v8.renderscript.RSRuntimeException: Error loading RS jni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.theotech.ceaselessandroid-1/base.apk"],nativeLibraryDirectories=[/data/app/org.theotech.ceaselessandroid-1/lib/arm64, /data/app/org.theotech.ceaselessandroid-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "librsjni.so"
	at android.support.v8.renderscript.RenderScript.internalCreate(RenderScript.java:1347)
	at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1504)
	at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1454)
	at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1430)
	at android.support.v8.renderscript.RenderScript.create(RenderScript.java:1417)
	at jp.wasabeef.picasso.transformations.BlurTransformation.transform(BlurTransformation.java:66)
	at com.squareup.picasso.BitmapHunter.applyCustomTransformations(BitmapHunter.java:429)
	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:238)
	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by chrislim** [comment]
This problem should be resolved now with a newer release of the android build tools.
